server:
  port: 8082

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml 
    
spring:
  application:
    name: msa-service-coffee-status

#Config Server      
  cloud:
    config:
      uri: http://localhost:8888 
      name: msa-architecture-config-server
 
#Kafka
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: consumerGroupId
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#Eureka Client   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/